name: dgtest
favicon: null
layout_spectrum: 0.06651426269672811
typography_spectrum: 0.3633982709143311
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#002454'
    - '#944900'
    - '#7691b4'
    - '#e5d1bc'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
