name: dgtest
favicon: null
layout_spectrum: 0.06651426269672811
typography_spectrum: 0.3633982709143311
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9050500576850027
  lightness: 0.053309263195842505
  saturation: 0.22907325811684132
  rhythmicContrast: 0.05555894272401929
purpose: []
